server.port: 9000

spring:
  mybatis:
    mapper-locations: "classpath*:**/mapper.xml"
    configuration-properties:
      aggressiveLazyLoading: false
      lazyLoadingEnabled: true
      lazyLoadTriggerMethods: ""
      mapUnderscoreToCamelCase: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

spring.datasource.url: jdbc:mysql://localhost/testmybatis
spring.datasource.username: testmybatis
spring.datasource.password: testmybatis
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    org.springframework.boot: DEBUG
    sample.springboot.mybatis: DEBUG
  
